spring:
  profiles:
    active: development
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    # noinspection SpellCheckingInspection
    url: jdbc:postgresql://db.nehdmglhmjoxjhyxljms.supabase.co:5432/postgres?user=postgres&password=wooDe.73warehouse
    username: postgres
    password: wooDe.73warehouse
socket-server:
  host: localhost
  port: 8086
---
spring:
  config:
    activate:
      on-profile: development
  devtools:
    add-properties: true
  mvc:
    log-request-details: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        "globally_quoted_identifiers": true
  security:
    debug: true
logging:
  level:
    web: DEBUG
---
spring:
  devtools:
    add-properties: false
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: update