spring:
  profiles:
    active: production
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    # noinspection SpellCheckingInspection
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.nehdmglhmjoxjhyxljms&password=wooDe.73warehouse
    username: postgres
    password: wooDe.73warehouse
server:
  address: 5.35.11.110
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: tomcat
security:
  require-ssl: true
socket-server:
  host: 5.35.11.110
  port: 80
---
spring:
  config:
    activate:
      on-profile: development
  devtools:
    add-properties: true
  mvc:
    log-request-details: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        "globally_quoted_identifiers": true
  security:
    debug: true
logging:
  level:
    web: DEBUG
---
spring:
  devtools:
    add-properties: false
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: create-drop
